output "cluster_endpoint" {
    description = "Endpoint for EKS control plane"
    value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
    description = "Security group ID attached to the EKS control plane"
    value       = module.eks.cluster_security_group_id
}

output "kubeconfig" {
    description = "Kubectl config as generated by the module"
    value       = local.kubeconfig
}

output "region" {
    description = "AWS region"
    value       = var.region
}
